export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const FETCH_LIKE_REQUEST = 'FETCH_LIKE_REQUEST';
export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS';
export const FETCH_LIKE_ERROR = 'FETCH_LIKE_ERROR';