export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_LIKE_REQUEST = 'FETCH_POSTS_LIKE_REQUEST';
export const FETCH_POSTS_LIKE_SUCCESS = 'FETCH_POSTS_LIKE_SUCCESS';
export const FETCH_POSTS_LIKE_ERROR = 'FETCH_POSTS_LIKE_ERROR';